blueprint:
  name: Namron 4 channel switch light control
  description: Control a light with a Namron 4 channel switch

  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: zha
          manufacturer: NAMRON AS

    light:
      name: Light
      description: Light to control
      selector:
        entity:
          filter:
            - domain: light

    button_num:
      name: Button number
      description: Button number
      default: 1
      selector:
        number:
          min: 1
          max: 4

    brightness_step_pct:
      name: Brightness step
      description: Brightness step in percent
      default: 10
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          step: 1

mode: restart
max_exceeded: silent

trigger:
  - id: "on"
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: "on"

  - id: "off"
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: "off"

  - id: onHold
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: move_with_on_off
      args:
        - 0
        - 50

  - id: onRelease
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: stop_with_on_off

  - id: offHold
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: move_with_on_off
      args:
        - 1
        - 50

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              entity_id: !input light
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: !input light
      - conditions:
          - condition: trigger
            id: onHold
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: !input brightness_step_pct
                  target:
                    entity_id: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 250
      - conditions:
          - condition: trigger
            id: offHold
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: {{ brightness_step_pct * (-1) }}
                  target:
                    entity_id: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 250


