blueprint:
  name: Namron 4 channel switch light control
  description: Control a light with a Namron 4 channel switch

  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: zha
          manufacturer: NAMRON AS

    light:
      name: Light
      description: Light to control
      selector:
        entity:
          filter:
            - domain: light

    button_num:
      name: Button number
      description: Button number
      default: 1
      selector:
        number:
          min: 1
          max: 4

    brightness_step_pct_down:
      name: Brightness step dim down
      description: Brightness step in percent when dimming down
      default: -2
      selector:
        number:
          min: -100
          max: -1
          mode: slider
          step: 1

    brightness_step_pct_up:
      name: Brightness step dim up
      description: Brightness step in percent
      default: 2
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          step: 1

    step_delay_milliseconds:
      name: Step delay milliseconds
      description: Delay between each step in milliseconds
      default: 110
      selector:
        number:
          min: 0
          max: 1000
          mode: slider
          step: 1

mode: restart
max_exceeded: silent

trigger:
  - id: "on"
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: "on"

  - id: "off"
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: "off"

  - id: onHold
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: move_with_on_off
      args:
        - 0
        - 50

  - id: offHold
    platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      endpoint_id: !input button_num
      command: move_with_on_off
      args:
        - 1
        - 50

  - id: offHold2
      platform: event
      event_type: zha_event
      event_data:
        device_id: !input remote
        endpoint_id: !input button_num
        command: move
        args:
          - 1
          - 50
          - 0
          - 0

condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: !input light
      - conditions:
          - condition: trigger
            id: onHold
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: !input brightness_step_pct_up
                  target:
                    entity_id: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay_milliseconds
      - conditions:
          - condition: trigger
            id: offHold
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: !input brightness_step_pct_down
                  target:
                    entity_id: !input light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay_milliseconds


      - conditions:
          - condition: trigger
            id: offHold2
          sequence:
            - repeat:
                while:
                  - condition: trigger
                    id: offHold2
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_step_pct: !input brightness_step_pct_down
                    target:
                      entity_id: !input light
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 0
                      milliseconds: !input step_delay_milliseconds

